# Generated by Django 4.1.2 on 2022-11-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.FileField(blank=True, null=True, upload_to='urunler/')),
                ('isim', models.CharField(max_length=300)),
                ('adet', models.CharField(max_length=300)),
                ('aciklama', models.TextField(max_length=500)),
                ('fiyat', models.IntegerField()),
            ],
        ),
    ]
