# Generated by Django 4.1.2 on 2022-11-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_alter_urun_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='urunler.altkategori'),
        ),
    ]
